#bundle exec rake db:populate
#bundle exec rake test:prepare
namespace :db do
  desc "Fill database with sample data"
  task populate: :environment do
    generatePlayersAndPositions
  end

  def generatePlayersAndPositions
    positionC = Position.create!(label:"C", name: "Catcher")
    positionP = Position.create!(label:"P", name: "Pitcher")
    position1B = Position.create!(label:"1B", name: "First Base")
    position2B = Position.create!(label:"2B", name: "Second Base")
    position3B = Position.create!(label:"3B", name: "Third Base")
    positionSS = Position.create!(label:"SS", name: "Shortstop")
    positionLF = Position.create!(label:"LF", name: "Left Field")
    positionLC = Position.create!(label:"LC", name: "Left Center")
    positionRF = Position.create!(label:"RF", name: "Right Field")
    positionRC = Position.create!(label:"RC", name: "Right Center")

    player1 = Player.create!(name: "Paige Ponzeka")
    setPosition(player1, positionP)
    setPosition(player1, position1B)
    setPosition(player1, position3B)
    player2 = Player.create!(name: "Andrew Flatgard")
    setPosition(player2, positionC)
    setPosition(player2, positionRF)
    setPosition(player2, positionRC)
    setPosition(player2, positionLF)
    setPosition(player2, positionLC)
    player3 = Player.create!(name: "Ricky Cratty")
    setPosition(player3, positionC)
    setPosition(player3, position2B)
    player4 = Player.create!(name: "William King")
    setPosition(player4, positionC)
    setPosition(player4, positionRF)
    setPosition(player4, positionRC)
    setPosition(player4, positionLF)
    setPosition(player4, positionLC)
    player5 = Player.create!(name: "Alex Joa")
    setPosition(player5, positionRF)
    setPosition(player5, positionRC)
    setPosition(player5, positionLF)
    setPosition(player5, positionLC)
    player6 = Player.create!(name: "Michael Burns")
    setPosition(player6, position1B)
    setPosition(player6, positionRF)
    setPosition(player6, positionRC)
    setPosition(player6, positionLF)
    setPosition(player6, positionLC)
    player7 = Player.create!(name: "Patrick Marley")
    setPosition(player7, position1B)
    player8 = Player.create!(name: "Stephanie Meireles")
    setPosition(player8, position3B)
    setPosition(player8, positionSS)
    player9= Player.create!(name: "Jose Collazo")
    setPosition(player9, position2B)
    player10= Player.create!(name: "Whitney Liriano")
    setPosition(player10, position1B)
    setPosition(player10, position2B)
    setPosition(player10, positionRF)
    setPosition(player10, positionRC)
    setPosition(player10, positionLF)
    setPosition(player10, positionLC)
    player11= Player.create!(name: "Krystal Gonzalez")
    setPosition(player11, position1B)
    setPosition(player11, position2B)
    setPosition(player11, positionRF)
    setPosition(player11, positionRC)
    setPosition(player11, positionLF)
    setPosition(player11, positionLC)
    player12= Player.create!(name: "Amanda Babine")
    setPosition(player12, positionSS)
    setPosition(player12, position3B)
    player13= Player.create!(name: "Kate Sarrantonio")
    setPosition(player13, position2B)
    setPosition(player13, positionRF)
    setPosition(player13, positionRC)
    setPosition(player13, positionLF)
    setPosition(player13, positionLC)
    player14 = Player.create!(name: "Lauren Holmes")
    setPosition(player14, positionC)
    setPosition(player14, positionRF)
    setPosition(player14, positionRC)
    setPosition(player14, positionLF)
    setPosition(player14, positionLC)
    player15 = Player.create!(name: "Emily Sperber")
    setPosition(player15, position1B)
    setPosition(player15, positionRF)
    setPosition(player15, positionRC)
    setPosition(player15, positionLF)
    setPosition(player15, positionLC)

    
  end

  def setPosition(player, position)
    PlayerPosition.create!(player_id: player.id, position_id: position.id )
  end


end